apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-spring-ingress
  namespace: user01
spec:
  ingressClassName: nginx
  rules:
  - host: user01-spring.com
    http:
      paths:
      - backend:
          service:
            name: hello-spring-svc
            port:
              number: 80
        path: /
        pathType: Prefix
